# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_ncurses"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
description = "Fortran interface to ncurses(3c)"
categories = ["screen formatting"]
keywords = ["fortran", "screen","API"]
homepage = "https://github.com/urbanjost/M_ncurses.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
#module-naming = true

link = "ncurses"

[install]
library = true
